export const LAYOUT_SIZES = {
  NAVIGATION_PANEL_WIDTH: 180,
  NAVIGATION_PANEL_COLLAPSED_WIDTH: 45,
  NAVIGATION_PANEL_MIN_WIDTH: 150,
  NAVIGATION_PANEL_MAX_WIDTH: 500,
  NAVIGATION_COLLAPSE_THRESHOLD: 100, // Below this width, auto-collapse
  NAVIGATION_EXPAND_THRESHOLD: 120, // Above this width, auto-expand
  NAVIGATION_FORCE_EXPAND_WIDTH: 200, // Above this width, always show expanded
  CONTENT_PANEL_MIN_WIDTH: 300,
  CONTENT_PANEL_MIN_HEIGHT: 200,
  DEFAULT_PANEL_WIDTH: 700,
  DEFAULT_PANEL_HEIGHT: 400,
  FULL_WIDTH: 1050,
  DIVIDER_SIZE: 4, // Size of resizable dividers
} as const;

export const DRAG_THRESHOLDS = {
  HORIZONTAL_ASPECT_RATIO: 2,
  VERTICAL_POSITION: 0.33,
  HORIZONTAL_POSITION: 0.33,
} as const;

export const ANIMATION_DURATIONS = {
  FAST: 150,
  NORMAL: 300,
  SLOW: 500,
} as const;
