export const LAYOUT_SIZES = {
  NAVIGATION_PANEL_WIDTH: 250,
  NAVIGATION_PANEL_COLLAPSED_WIDTH: 59,
  NAVIGATION_PANEL_MIN_WIDTH: 59,
  NAVIGATION_PANEL_MAX_WIDTH: 400,
  NAVIGATION_COLLAPSE_THRESHOLD: 80, // Below this width, auto-collapse
  NAVIGATION_EXPAND_THRESHOLD: 120, // Above this width, auto-expand
  CONTENT_PANEL_MIN_WIDTH: 250,
  DEFAULT_PANEL_WIDTH: 700,
  FULL_WIDTH: 1050,
} as const;

export const DRAG_THRESHOLDS = {
  HORIZONTAL_ASPECT_RATIO: 2,
  VERTICAL_POSITION: 0.33,
  HORIZONTAL_POSITION: 0.33,
} as const;

export const ANIMATION_DURATIONS = {
  FAST: 150,
  NORMAL: 300,
  SLOW: 500,
} as const;
